name: docs

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  run:
    continue-on-error: True
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run:  |
        pip install tox
        sudo apt-get install -y graphviz libgraphviz-dev
    - name: Generate Documentation
      run: tox -e docs
