name: lint

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  run:
    continue-on-error: True
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run:  |
        pip install tox
        sudo apt-get install -y graphviz libgraphviz-dev
    - name: Pylint
      run: tox -e pylint
    - name: Code style check
      run: |
        tox -e black-check
        tox -e isort-check
        tox -e flake8
        tox -e vulture
        tox -e darglint
    - name: Static type check
      run: tox -e mypy
    - name: Check copyright
      run: tox -e check-copyright
    - name: Misc checks
      run: |
        tox -e bandit
        tox -e safety
