name: test

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  run:
    continue-on-error: True
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        python-version: [3.7] #, 3.8, 3.9]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run:  |
        pip install tox
        sudo apt-get install -y graphviz libgraphviz-dev
      #    # set up environment depending on the platform in use
#    - if: matrix.os == 'ubuntu-latest'
#      name: Install dependencies (ubuntu-latest)
#      run: ...
#    - if: matrix.os == 'macos-latest'
#      name: Install dependencies (macos-latest)
#      run: ...
#    - if: matrix.os == 'windows-latest'
#      name: Install dependencies (windows-latest)
#      env:
#        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
#      run: ...
    - name: Unit tests and coverage
      run: |
        tox -e py${{ matrix.python-version }}
